import { Content, Language } from './types';

const galleryImages = [
  { id: 1, src: 'https://picsum.photos/1200/800?random=101', title: 'Industrial Ventilation Unit', category: 'HVAC' },
  { id: 2, src: 'https://picsum.photos/1200/800?random=102', title: 'Main Distribution Board', category: 'Electrical' },
  { id: 3, src: 'https://picsum.photos/1200/800?random=103', title: 'Commercial Fire Pump', category: 'Fire Safety' },
  { id: 4, src: 'https://picsum.photos/1200/800?random=104', title: 'Smart Building Control Center', category: 'Automation' },
  { id: 5, src: 'https://picsum.photos/1200/800?random=105', title: 'Luxury Hotel Plumbing', category: 'Plumbing' },
];

export const content: Record<Language, Content> = {
  en: {
    nav: {
      links: [
        { label: 'Home', href: '#home' },
        { label: 'About', href: '#about' },
        { label: 'Services', href: '#services' },
        { label: 'Gallery', href: '#gallery' },
        { label: 'Projects', href: '#projects' },
        { label: 'Why Us', href: '#why-us' },
        { label: 'Contact', href: '#contact' },
      ],
    },
    hero: {
      title: 'EL ALAMYA ELECTROMECHANICAL',
      subtitle: 'Delivering excellence in engineering with sustainable, high-quality systems for industrial, commercial, and residential sectors.',
      ctaPrimary: 'Contact Us',
      ctaSecondary: 'Our Services',
      stats: [
        { label: 'Years Experience', value: '15+' },
        { label: 'Projects Completed', value: '250+' },
        { label: 'Happy Clients', value: '100+' },
      ],
    },
    about: {
      title: 'About EL ALAMYA',
      description: 'We are a premier engineering firm specializing in Mechanical, Electrical, and Plumbing (MEP) solutions. Our multidisciplinary team ensures seamless integration of complex systems.',
      specializations: ['Industrial Engineering', 'Smart Automation', 'Sustainable Energy', 'Complex Infrastructure'],
      valuesTitle: 'Core Values',
      values: ['Integrity', 'Innovation', 'Sustainability', 'Safety First'],
      teamTitle: 'Our Team',
      teamText: 'A dedicated group of certified engineers, project managers, and technicians working in unison to deliver precision.',
    },
    visionMission: {
      visionTitle: 'Our Vision',
      visionText: 'To be the regional leader in electromechanical innovation, setting benchmarks for quality and sustainability.',
      missionTitle: 'Our Mission',
      missionText: 'To provide integrated, efficient, and reliable engineering solutions that exceed client expectations while safeguarding the environment.',
    },
    services: {
      title: 'Our Expertise',
      learnMore: 'View Details',
      close: 'Close Details',
      items: [
        {
          id: 'hvac',
          title: 'HVAC Solutions',
          description: 'Comprehensive Heating, Ventilation, and Air Conditioning systems designed for optimal climate control and air quality.',
          solutions: ['Central Air Conditioning', 'VRF Systems', 'Ventilation & Exhaust', 'Chilled Water Systems'],
          process: ['Load Calculation', 'Duct Design', 'Installation', 'Maintenance'],
          sectors: ['Commercial Towers', 'Hospitals', 'Factories'],
          iconName: 'Fan',
        },
        {
          id: 'electrical',
          title: 'Electrical & ELV Systems',
          description: 'Power distribution, lighting, and low current systems ensuring operational reliability.',
          solutions: ['Medium & Low Voltage Distribution', 'Lighting Control', 'Data Networks', 'Power Generators'],
          process: ['Grid Analysis', 'Cable Tray Layout', 'Testing & Commissioning'],
          sectors: ['Industrial Plants', 'Office Buildings', 'Data Centers'],
          iconName: 'Zap',
        },
        {
          id: 'plumbing',
          title: 'Plumbing Systems',
          description: 'Advanced water supply and drainage solutions tailored for hygiene and efficiency.',
          solutions: ['Water Supply Networks', 'Drainage Systems', 'Water Treatment', 'Pumping Stations'],
          process: ['Hydraulic Design', 'Piping Layout', 'Leak Testing'],
          sectors: ['Residential Complexes', 'Hotels', 'Public Facilities'],
          iconName: 'Droplets',
        },
        {
          id: 'fire',
          title: 'Fire Fighting & Safety',
          description: 'Certified life safety systems designed to protect people and assets.',
          solutions: ['Sprinkler Systems', 'Fire Alarms', 'FM200 / CO2 Systems', 'Smoke Management'],
          process: ['Risk Assessment', 'NFPA Compliance Design', 'Civil Defense Approval'],
          sectors: ['Warehouses', 'Shopping Malls', 'High-rise Buildings'],
          iconName: 'Flame',
        },
        {
          id: 'heating',
          title: 'Heating Systems',
          description: 'Central heating solutions for ultimate comfort in colder climates.',
          solutions: ['Underfloor Heating', 'Boilers', 'Radiators', 'Solar Water Heating'],
          process: ['Thermal Modelling', 'Pipe Insulation', 'System Balancing'],
          sectors: ['Luxury Villas', 'Resorts', 'Spas'],
          iconName: 'ThermometerSun',
        },
        {
          id: 'smart',
          title: 'Intelligent Systems',
          description: 'Future-ready building automation and security integration.',
          solutions: ['BMS (Building Management Systems)', 'CCTV & Access Control', 'Smart Home Automation', 'IoT Sensors'],
          process: ['System Architecture', 'Integration', 'User Training'],
          sectors: ['Smart Cities', 'Secure Facilities', 'Modern Offices'],
          iconName: 'Cpu',
        },
      ],
    },
    gallery: {
        title: 'Our Work Gallery',
        description: 'A visual tour of our excellence in execution.',
        items: galleryImages,
    },
    projects: {
      title: 'Projects & Clients',
      categories: [
        { title: 'Commercial', items: ['City Mall Expansion', 'Skyline Office Tower', 'Tech Park HQ'] },
        { title: 'Industrial', items: ['Al-Safa Steel Factory', 'Global Logistics Warehouse', 'Pharma Plant Alpha'] },
        { title: 'Residential', items: ['Palm Jumeirah Villas', 'Sunset Residence Complex', 'Royal Heights'] },
      ],
    },
    partners: {
      title: 'Our Strategic Partners',
      description: 'Collaborating with world-class manufacturers to deliver the best components.',
    },
    whyUs: {
      title: 'Why Choose Us?',
      features: [
        { title: 'Integrated Solutions', desc: 'One-stop shop for all MEP needs.' },
        { title: 'Engineering Expertise', desc: 'Highly qualified certified engineers.' },
        { title: 'Quality Assurance', desc: 'ISO certified processes and rigorous testing.' },
        { title: 'Timely Delivery', desc: 'Strict adherence to project timelines.' },
        { title: 'After-Sales Support', desc: '24/7 maintenance and facility management.' },
      ],
    },
    contact: {
      title: 'Get In Touch',
      form: {
        name: 'Full Name',
        email: 'Email Address',
        phone: 'Phone Number',
        message: 'Your Message',
        submit: 'Send Message',
      },
      info: {
        address: '123 Business Bay, Innovation Tower, Floor 15',
        phone: '+971 4 123 4567',
        email: 'info@promep-solutions.com',
      },
    },
    footer: {
      rights: '© 2024 EL ALAMYA ELECTROMECHANICAL. All Rights Reserved.',
    },
  },
  ar: {
    nav: {
      links: [
        { label: 'الرئيسية', href: '#home' },
        { label: 'من نحن', href: '#about' },
        { label: 'خدماتنا', href: '#services' },
        { label: 'معرض الصور', href: '#gallery' },
        { label: 'مشاريعنا', href: '#projects' },
        { label: 'لماذا نحن', href: '#why-us' },
        { label: 'تواصل معنا', href: '#contact' },
      ],
    },
    hero: {
      title: 'العالمية إليكترو ميكانيكال',
      subtitle: 'نقدم التميز الهندسي من خلال أنظمة مستدامة وعالية الجودة للقطاعات الصناعية والتجارية والسكنية.',
      ctaPrimary: 'تواصل معنا',
      ctaSecondary: 'خدماتنا',
      stats: [
        { label: 'سنوات خبرة', value: '+15' },
        { label: 'مشروع مكتمل', value: '+250' },
        { label: 'عميل سعيد', value: '+100' },
      ],
    },
    about: {
      title: 'عن الشركة',
      description: 'نحن شركة هندسية رائدة متخصصة في حلول الميكانيكا والكهرباء والسباكة (MEP). يضمن فريقنا متعدد التخصصات تكاملاً سلسًا للأنظمة المعقدة.',
      specializations: ['الهندسة الصناعية', 'الأتمتة الذكية', 'الطاقة المستدامة', 'البنية التحتية المعقدة'],
      valuesTitle: 'قيمنا الأساسية',
      values: ['النزاهة', 'الابتكار', 'الاستدامة', 'السلامة أولاً'],
      teamTitle: 'فريق العمل',
      teamText: 'مجموعة متفانية من المهندسين المعتمدين ومديري المشاريع والفنيين يعملون بانسجام لتقديم الدقة.',
    },
    visionMission: {
      visionTitle: 'رؤيتنا',
      visionText: 'أن نكون القائد الإقليمي في الابتكار الكهروميكانيكي، ووضع معايير للجودة والاستدامة.',
      missionTitle: 'رسالتنا',
      missionText: 'تقديم حلول هندسية متكاملة وفعالة وموثوقة تتجاوز توقعات العملاء مع الحفاظ على البيئة.',
    },
    services: {
      title: 'مجالات تخصصنا',
      learnMore: 'عرض التفاصيل',
      close: 'إغلاق',
      items: [
        {
          id: 'hvac',
          title: 'حلول التكييف والتهوية',
          description: 'أنظمة تدفئة وتهوية وتكييف شاملة مصممة للتحكم الأمثل في المناخ وجودة الهواء.',
          solutions: ['التكييف المركزي', 'أنظمة VRF', 'التهوية وسحب الدخان', 'أنظمة المياه المبردة (Chillers)'],
          process: ['حساب الأحمال', 'تصميم الدكت', 'التركيب', 'الصيانة'],
          sectors: ['الأبراج التجارية', 'المستشفيات', 'المصانع'],
          iconName: 'Fan',
        },
        {
          id: 'electrical',
          title: 'الأنظمة الكهربائية والتيار الخفيف',
          description: 'توزيع الطاقة، الإضاءة، والأنظمة منخفضة التيار لضمان الموثوقية التشغيلية.',
          solutions: ['توزيع الجهد المتوسط والمنخفض', 'التحكم في الإضاءة', 'شبكات البيانات', 'مولدات الطاقة'],
          process: ['تحليل الشبكة', 'مخططات الكابلات', 'الاختبار والتشغيل'],
          sectors: ['المنشآت الصناعية', 'المباني الإدارية', 'مراكز البيانات'],
          iconName: 'Zap',
        },
        {
          id: 'plumbing',
          title: 'أنظمة السباكة والصرف',
          description: 'حلول متقدمة لإمدادات المياه والصرف الصحي مصممة للنظافة والكفاءة.',
          solutions: ['شبكات تغذية المياه', 'أنظمة الصرف الصحي', 'معالجة المياه', 'محطات الضخ'],
          process: ['التصميم الهيدروليكي', 'مخططات الأنابيب', 'اختبار التسريب'],
          sectors: ['المجمعات السكنية', 'الفنادق', 'المرافق العامة'],
          iconName: 'Droplets',
        },
        {
          id: 'fire',
          title: 'مكافحة الحريق والسلامة',
          description: 'أنظمة سلامة معتمدة مصممة لحماية الأرواح والممتلكات.',
          solutions: ['أنظمة الرش الآلي', 'إنذار الحريق', 'أنظمة FM200 / CO2', 'إدارة الدخان'],
          process: ['تقييم المخاطر', 'تصميم مطابق لـ NFPA', 'اعتماد الدفاع المدني'],
          sectors: ['المستودعات', 'مراكز التسوق', 'المباني الشاهقة'],
          iconName: 'Flame',
        },
        {
          id: 'heating',
          title: 'أنظمة التدفئة المركزية',
          description: 'حلول تدفئة مركزية لراحة قصوى في المناخات الباردة.',
          solutions: ['التدفئة تحت البلاط', 'المراجل (Boilers)', 'الدفايات', 'سخانات المياه الشمسية'],
          process: ['النمذجة الحرارية', 'عزل الأنابيب', 'موازنة النظام'],
          sectors: ['الفلل الفاخرة', 'المنتجعات', 'النوادي الصحية'],
          iconName: 'ThermometerSun',
        },
        {
          id: 'smart',
          title: 'الأنظمة الذكية',
          description: 'أتمتة المباني والتكامل الأمني للمستقبل.',
          solutions: ['أنظمة إدارة المباني (BMS)', 'كاميرات المراقبة والتحكم في الدخول', 'أتمتة المنازل الذكية', 'حساسات IoT'],
          process: ['هندسة النظام', 'التكامل والربط', 'تدريب المستخدمين'],
          sectors: ['المدن الذكية', 'المرافق المؤمنة', 'المكاتب الحديثة'],
          iconName: 'Cpu',
        },
      ],
    },
    gallery: {
        title: 'معرض الأعمال',
        description: 'جولة بصرية تعكس تميزنا في التنفيذ والدقة.',
        items: galleryImages,
    },
    projects: {
      title: 'المشاريع والعملاء',
      categories: [
        { title: 'تجاري', items: ['توسعة سيتي مول', 'برج سكاي لاين المكتبي', 'مقر واحة التكنولوجيا'] },
        { title: 'صناعي', items: ['مصنع الصفا للحديد', 'مستودعات جلوبال اللوجستية', 'مصنع فارما ألفا'] },
        { title: 'سكني', items: ['فلل نخلة جميرا', 'مجمع غروب الشمس السكني', 'رويال هايتس'] },
      ],
    },
    partners: {
      title: 'شركاؤنا الاستراتيجيين',
      description: 'نتعاون مع مصنعين عالميين لتقديم أفضل المكونات والأنظمة.',
    },
    whyUs: {
      title: 'لماذا تختارنا؟',
      features: [
        { title: 'حلول متكاملة', desc: 'محطة واحدة لجميع احتياجات MEP.' },
        { title: 'خبرة هندسية', desc: 'مهندسون معتمدون ذوو كفاءة عالية.' },
        { title: 'ضمان الجودة', desc: 'عمليات معتمدة من ISO واختبارات صارمة.' },
        { title: 'الالتزام بالمواعيد', desc: 'الالتزام الصارم بالجداول الزمنية للمشروع.' },
        { title: 'خدمة ما بعد البيع', desc: 'صيانة وإدارة مرافق على مدار الساعة.' },
      ],
    },
    contact: {
      title: 'تواصل معنا',
      form: {
        name: 'الاسم الكامل',
        email: 'البريد الإلكتروني',
        phone: 'رقم الهاتف',
        message: 'رسالتك',
        submit: 'إرسال الرسالة',
      },
      info: {
        address: '123 الخليج التجاري، برج الابتكار، طابق 15',
        phone: '+971 4 123 4567',
        email: 'info@promep-solutions.com',
      },
    },
    footer: {
      rights: '© 2024 العالمية إليكترو ميكانيكال. جميع الحقوق محفوظة.',
    },
  },
};